# Generated by Django 5.0.4 on 2024-04-25 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_events_related_user_profile_expired_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='dislikers',
            field=models.ManyToManyField(null=True, related_name='Dislikers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='events',
            name='likers',
            field=models.ManyToManyField(null=True, related_name='Likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
