# Generated by Django 5.0.4 on 2024-05-01 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_alter_events_dislikers_alter_events_likers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='dislikers',
            field=models.ManyToManyField(blank=True, related_name='Dislikers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='events',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='Likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
